### ISSUE TITLE
Content - Beneficiary Engagement

### ISSUE THREAD

**Issue by WanderZ** [NUSComputingDev/freshmen.nuscomputing.com#1]
Is it possible to add in the Beneficiary Engagement inside the timeline?

The details can be extracted from this link: http://tiny.cc/flagfgs

Source: https://www.facebook.com/SoCFOP/posts/1093187814086409

**Comment by nicholaslum444** [comment]
@ZhangYiJiang or @lweikit please take note

**Comment by ZhangYiJiang** [comment]
Staging server has been updated - https://meebleforp.com/projects/fop/. If there are no errors please push to production.
