### ISSUE TITLE
Update committee photos and titles

### ISSUE THREAD

**Issue by leeyimin** [NUSComputingDev/freshmen.nuscomputing.com#25]
Requires:
* photos and titles from FOP

- [x] Remove grayscale filter in sass files
- [ ] Update images in assets/img (Follow same title format)

**Comment by jia1** [comment]
We don't want same title format because it violates file naming in Windows == can't check out in Windows urgh!

**Comment by leeyimin** [comment]
Images are now uploaded at: https://drive.google.com/drive/u/1/folders/0B3RUPRRu3cj1eXZnRmw3RU5ITU0 (to be moved to more accessible location)

**Comment by leeyimin** [comment]
@jia1 Seems like that just requires small changes to gulpfile.js!

**Comment by jia1** [comment]
Line 62 right?

The file name also very long...
